### PR TITLE
Include code for odometry calibration

### PR DESCRIPTION
**Pull request by Alkarex**
### Calib C Code
The code is used to calibrate the odometry of the Arlobot.
The encoders must be plugged in the Parallax activity board, and the DISPERCOUNT, TRACKWIDTH and DIAERROR should be calibrated.
`Fwd()` and `Turn()` functions are used to drive the robot to a certain distance or angle.
The calibrated results shoud be put into the copy of `../src/arlobot/arlobot_bringup/arlobot.yaml`, which is under `~/.arlobot/`.

A typical cablibration method can be found in
"[Borenstein, J., & Feng, L. (1995). UMBmark: A benchmark test for measuring odometry errors in mobile robots](http://dx.doi.org/10.1117/12.228968). Ann Arbor, 1001, 48109-2110."

### CODE REVIEW

**Comment by chrisl8** [comment]
@Alkarex Can you explain further how this should be used?

1. You mention adding the results to arlobot.yaml, but I do not see where they are used in code.
When and where are they read and used?

2. You provided a link to a document, but when I follow the link it requires payment to actually read it.
Do I need to read the linked document to use this code?
If not, how exactly should somebody go about calibrating their Arlobot?

Thank you.

**Comment by Alkarex** [comment]
@chrisl8 My colleague @ZhongyuWang has added some more explanations in the README.
Let us know whether it is clear enough.

**Comment by chrisl8** [comment]
Sorry I was so slow to merge this. I hope it hasn't hindered your progress.

**Comment by Alkarex** [comment]
@chrisl8 No worries, and thanks for merging.
We are just back from Easter vacations, but we continue, and I expect we will send a few more small improvements :-)
We still have some instability with the DHB-10 motor board and other problems with the Arlo, but it is better than it used to be.

**Pull request merged**
